routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home'); 

Route::group(['prefix' => 'user', 'middleware' => ['auth']], function ($app) {
   Route::resource('user', 'UserController');
   Route::get('/', 'UserController@index'); 
   Route::get('/create', ['uses' => 'UserController@create', 'as' => 'user.create']);
   Route::put('/destroy', 'UserController@destroy');
   Route::get('/detail', ['uses' => 'UserController@detail', 'as' => 'user.detail']); 

   // cars
   Route::get('/cars', ['uses' => 'CarController@index', 'as' => 'cars']);
   Route::get('/addCar','CarController@create')->name('addCar');
   Route::post('addCarForm', ['uses' => 'CarController@store', 'as' => 'addCarForm']); 

   Route::get('edit/{id}', ['uses' => 'CarController@edit', 'as' => 'edit']);
   Route::post('edit/{id}','CarController@update');
   Route::delete('{id}','CarController@destroy');

   // company
   Route::get('/company', ['uses' => 'CompanyController@index', 'as' => 'company']);
   Route::get('/addCompany','CompanyController@create')->name('addCompany');
   Route::post('addCompanyForm', ['uses' => 'CompanyController@store', 'as' => 'addCompanyForm']); 

   Route::get('editCompany/{id}', ['uses' => 'CompanyController@edit', 'as' => 'editCompany']);
   Route::post('editCompany/{id}','CompanyController@update');
   Route::delete('deleteCompany/{id}','CompanyController@destroy');
}); 

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Auth\Authenticatable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract; 
use Jenssegers\Mongodb\Eloquent\Model;

class User extends Model implements 
    AuthenticatableContract
{
    use Notifiable, Authenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['display_name', 'username', 'email', 'password'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $user) { 
        return view('user/index', ['users' => $user::get()]); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('user.create');
    }

    /**
     * @param Request $request
     * 
     */
    public function store(Request $request) {
        User::create([
            'username'      => $request->get('username'),
            'display_name'  => $request->get('display_name'), 
            'email'         => $request->get('email'),
            'password'      => bcrypt($request->get('password'))
        ]);

        return redirect()->route('user.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) { 
        $user = User::find($id);
        return view('user.edit',['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function detail(Request $request) { 
        $id = $request->get('id');
        $user = User::find($id);
        return view('user.view',['user' => $user]);
    }

    /**
     * @param Request $request
     * @param         $id
     * 
     */
    public function update(Request $request, $id) {
        $user = User::find($id);

        $user->username = $request->get('username');
        $user->display_name = $request->get('display_name');
        $user->email = $request->get('email'); 

        if($request->get('password') != '')
        {
            $user->password = bcrypt($request->get('password'));
        }

        $user->save();
        return redirect()->route('user.index');
    }

    public function destroy(Request $request) {     
        $id = $request->get('id');
        $user = User::destroy($id);

        if($user){
            $request->session()->invalidate();
            return $user;
        }
    }
}

resources/views/user/create.blade.php
 @extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Input User</div>

                <div class="panel-body">
                     <div class="col-md-13">
                            <!-- BEGIN BORDERED TABLE PORTLET-->
                            <div class="portlet light portlet-fit bordered"> 
                                <div class="portlet-body form">
                                    <form action="{{route('user.store')}}" method="post"> {{csrf_field()}}
                                        <div class="form-body">
                                            <div class="form-group">
                                                <label for="display_name">Name</label>
                                                <input type="text" name="display_name" id="display_name" placeholder="Name" class="form-control"/>
                                            </div>
                                            <div class="form-group">
                                                <label for="username">Username</label>
                                                <input type="text" name="username" id="username" placeholder="Username"
                                                       class="form-control"/>
                                            </div>
                                            <div class="form-group">
                                                <label for="email">Email</label>
                                                <input type="email" name="email" id="email" placeholder="Email" class="form-control"/>
                                            </div> 
                                            <div class="form-group">
                                                <label for="password">Password</label>
                                                <input type="password" name="password" id="password" placeholder="Password" class="form-control"/>
                                            </div>   
                                        </div>
                                        <div class="form-actions right1">
                                            <button type="submit" class="btn blue">Submit</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <!-- END BORDERED TABLE PORTLET-->
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Update User</div>

                <div class="panel-body">
                     <div class="col-md-13">
                            <!-- BEGIN BORDERED TABLE PORTLET-->
                            <div class="portlet light portlet-fit bordered"> 
                                <div class="portlet-body form">
                                    {!! Form::model($user, ['route' => ['user.update', $user->_id], 'method' => 'PUT', 'id' => 'form-edit']) !!}

                                <div class="alert-wrapper"></div>

                                <div class="form-body">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        {!! Form::text('display_name', null, ['id'=>"name", 'placeholder'=>"Name", 'class'=>"form-control", 'required']) !!}
                                    </div>
                                    <div class="form-group">
                                        <label for="username">Username</label>
                                        {!! Form::text('username', null, ['id'=>"username", 'placeholder'=>"Username", 'class'=>"form-control", 'required']) !!}

                                    </div>
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        {!! Form::email('email', null, ['id'=>"email", 'placeholder'=>"Email", 'class'=>"form-control"], 'required') !!}

                                    </div>  
                                    <div class="form-group">
                                        <label for="name">Password <br><small class="text-danger">Type to change password, left empty to use old password.</small></label>
                                        <input type="password" name="password" id="password" placeholder="Type to change password" class="form-control"/>
                                    </div> 
                                </div>

                                <button type="submit" class="btn btn-info btn-block btn-lg save">
                                    Update
                                </button>
                                {!! Form::close() !!} 
                                </div>
                            </div>
                            <!-- END BORDERED TABLE PORTLET-->
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function(){ 
        var id = '';
        $(".myBtn").click(function(){ 
            console.log($(this).data('id'));
            id = $(this).data('id');
            $("#myModal").modal();
        });

        $(".delete").click(function(){ 
            console.log(id);

            var data = {
                        '_token'        : "{{ csrf_token() }}",
                        'id'         : id 
                    }; 

             $.ajax({
                url: "user/destroy",
                type: 'PUT',
                data: data,
                dataType: "JSON", 
                success: function(result) {
                   console.log("sukses");
                   location.reload();
                }
            });
        });
       
    });
</script> 
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>
                <div class="panel-body">
                    You are logged in {{Auth::user()->display_name}} ! 
                </div>
                <div class="panel-body">
                     <div class="col-md-13">
                            <!-- BEGIN BORDERED TABLE PORTLET-->
                            <div class="portlet light portlet-fit bordered">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="icon-settings font-red"></i>
                                        <span class="caption-subject font-red sbold uppercase">User Table</span>
                                    </div> 
                                    <div class="actions pull-right" > 
                                       
                                        <a href="user/create" style="cursor: pointer;">
                                            <label class="btn btn-default" style="cursor: pointer;">
                                                <i class="fa fa-edit"></i> 
                                            Add 
                                            </label>
                                        </a>
                                        
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div class="table-scrollable table-scrollable-borderless">
                                        <table class="table table-hover table-light">
                                            <thead>
                                                <tr class="uppercase">
                                                    <th> No </th>
                                                    <th> First Name </th>
                                                    <th> Last Name </th>
                                                    <th> Username </th> 
                                                    <th> Action </th>
                                                </tr>
                                            </thead>
                                            <tbody> 
                                                <?php 
                                                    $no = 1;
                                                 ?>
                                                @foreach($users as $user) 
                                                    <tr>
                                                        <td> {{$no}} </td>
                                                        <td> {{$user->username}} </td>
                                                        <td> {{$user->display_name}} </td>
                                                        <td> {{$user->email}} </td> 
                                                        <td>

                                            
                                                            <a href="{{route('user.edit', $user->id)}}" class="btn btn-outline btn-circle btn-sm purple">
                                                            <i class="fa fa-edit"></i> Edit </a> 

                                         <a href="#" class="btn btn-outline btn-circle dark btn-sm black myBtn" data-id="{{$user->id}}">
                                                            <i class="fa fa-trash-o"></i> Delete </a>
                                                            </td>
                
                                                    </tr> 
                                                     <?php $no++; ?>
                                                @endforeach 


                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <!-- END BORDERED TABLE PORTLET-->
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Delete</h4>
        </div>
        <div class="modal-body">
          <p>Are you sure want to delete?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default delete" data-dismiss="modal">Yes</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
        </div>
      </div>
      
    </div>
  </div>
@endsection 
  

resources/views/user/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">View User</div>

                <div class="panel-body">
                     <div class="col-md-13">
                            <!-- BEGIN BORDERED TABLE PORTLET-->
                            <div class="portlet light portlet-fit bordered"> 
                                <div class="portlet-body form">
                                    {!! Form::model($user, ['route' => ['user.update', $user->_id], 'method' => 'PUT', 'id' => 'form-edit']) !!}

                                <div class="alert-wrapper"></div>

                                <div class="form-body">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        {!! Form::text('display_name', null, ['id'=>"name", 'placeholder'=>"Name", 'class'=>"form-control", 'required','readonly' => "readonly"]) !!}
                                    </div>
                                    <div class="form-group">
                                        <label for="username">Username</label>
                                        {!! Form::text('username', null, ['id'=>"username", 'placeholder'=>"Username", 'class'=>"form-control", 'required','readonly' => "readonly"]) !!}

                                    </div>
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        {!! Form::email('email', null, ['id'=>"email", 'placeholder'=>"Email", 'class'=>"form-control",'readonly' => "readonly"], 'required') !!}

                                    </div>   
                                </div> 
                                {!! Form::close() !!} 
                                </div>
                            </div>
                            <!-- END BORDERED TABLE PORTLET-->
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection