routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home'); 

Route::group(['prefix' => 'user', 'middleware' => ['auth']], function ($app) {
   Route::resource('user', 'UserController');
   Route::get('/', 'UserController@index'); 
   Route::get('/create', ['uses' => 'UserController@create', 'as' => 'user.create']);
   Route::put('/destroy', 'UserController@destroy');
   Route::get('/detail', ['uses' => 'UserController@detail', 'as' => 'user.detail']); 

   // cars
   Route::get('/cars', ['uses' => 'CarController@index', 'as' => 'cars']);
   Route::get('/addCar','CarController@create')->name('addCar');
   Route::post('addCarForm', ['uses' => 'CarController@store', 'as' => 'addCarForm']); 

   Route::get('edit/{id}', ['uses' => 'CarController@edit', 'as' => 'edit']);
   Route::post('edit/{id}','CarController@update');
   Route::delete('{id}','CarController@destroy');

   // company
   Route::get('/company', ['uses' => 'CompanyController@index', 'as' => 'company']);
   Route::get('/addCompany','CompanyController@create')->name('addCompany');
   Route::post('addCompanyForm', ['uses' => 'CompanyController@store', 'as' => 'addCompanyForm']); 

   Route::get('editCompany/{id}', ['uses' => 'CompanyController@edit', 'as' => 'editCompany']);
   Route::post('editCompany/{id}','CompanyController@update');
   Route::delete('deleteCompany/{id}','CompanyController@destroy');
}); 

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Car Crud') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Car Crud') }} 
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li><a href="{{ route('cars') }}">Add Car</a></li>
                            <li><a href="{{ route('company') }}">Add Company</a></li>
                            <li><a href="{{ url('/user') }}">Users</a></li>
                            <li><a href="{{ route('login') }}">{{ Auth::user()->email }}</a></li>
                            <li >
                                  <a href="{{route('user.edit', Auth::user()->id)}}">Setting</a>
                            </li>
                            <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>

                            <!-- <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->email }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                    <li >
                                        <a href="{{route('user.edit', Auth::user()->id)}}">Setting</a>
                                    </li>
                                </ul>
                            </li> -->
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>